version: '3.4'

services:
  techlabfzebe:
    image: techlabfzebe
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      HTTP_PORT: 8080
      CLIENT_ID: 861c78ea087a43aebc67938d804008ed
      CLIENT_SECRET: 79ded7f016e04bdd9f57b079f77355c4
      REDIS_URL: redis
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
    links:
      - mongodb
      - redis
    depends_on:
      - redis
    networks:
      - backend 
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    networks:
      - backend 
  redis:
    image: redis:alpine
    restart: always
    container_name: redis-alpine
    ports:
      - 6379:6379
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    volumes:
      - data:/data/cache
    networks:
      - backend 

networks:
  backend:
    driver: bridge

volumes:
  data:
    
